version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      roslyn:
        patterns: ["Microsoft.CodeAnalysis.*"]
      vssdk:
        patterns: ["Microsoft.VisualStudio.*", "Microsoft.VSSDK.*", "Microsoft.VsSDK.*", "Community.VisualStudio.*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
